// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfptQdB_k-OTfg5ybtWLjFw8Rv6q0WEZo',
    appId: '1:817095525310:web:ca18f097e3e30171336fef',
    messagingSenderId: '817095525310',
    projectId: 'chat-app-fe11d',
    authDomain: 'chat-app-fe11d.firebaseapp.com',
    storageBucket: 'chat-app-fe11d.firebasestorage.app',
    measurementId: 'G-E5RFV9ZJ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcb7XvdrMIfuUdq1rOZT_m4ncS4b-eL_8',
    appId: '1:817095525310:android:b53cfe7bd3a8ca1d336fef',
    messagingSenderId: '817095525310',
    projectId: 'chat-app-fe11d',
    storageBucket: 'chat-app-fe11d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADHVUL_2qzgFKlKZU-mu4fTgLPo1TL-zc',
    appId: '1:817095525310:ios:87995243d066eeac336fef',
    messagingSenderId: '817095525310',
    projectId: 'chat-app-fe11d',
    storageBucket: 'chat-app-fe11d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADHVUL_2qzgFKlKZU-mu4fTgLPo1TL-zc',
    appId: '1:817095525310:ios:87995243d066eeac336fef',
    messagingSenderId: '817095525310',
    projectId: 'chat-app-fe11d',
    storageBucket: 'chat-app-fe11d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfptQdB_k-OTfg5ybtWLjFw8Rv6q0WEZo',
    appId: '1:817095525310:web:db4e3f56d6cb4768336fef',
    messagingSenderId: '817095525310',
    projectId: 'chat-app-fe11d',
    authDomain: 'chat-app-fe11d.firebaseapp.com',
    storageBucket: 'chat-app-fe11d.firebasestorage.app',
    measurementId: 'G-EPZFLPKD53',
  );
}
